server:
  port: 8088
  servlet:
    context-path: /uapi
    session:
      timeout: 3600
    multipart:
      # 单个文件大小
      max-file-size: 1MB
      # 一次性上传文件的大小
      max-request-size: 1MB
  tomcat:
    accesslog:
      enabled: true
      suffix: .log
      prefix: access_log
      file-date-format: .yyyy-MM-dd
      directory: logs
      pattern: common
    basedir: tomcat
    # Tomcat在Tomcat 7.0.73+，Tomcat 8.0.39+，Tomcat 8.5.7+，Tomcat 9.0.0.M12 (markt)+版本后，
    # 在http url解析时做了严格字符限制，url包含特殊字符将直接返回http code 400
    relaxedQueryChars: <,>, [,],^,`,{,|,},%,&,\,_

spring:
  profiles:
    active:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/smms?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&createDatabaseIfNotExist=true&nullCatalogMeansCurrent=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  jpa:
    open-in-view: true
    show-sql: true # 默认false，在日志里显示执行的sql语句
    database: mysql
#    properties:
    hibernate:
      ddl-auto: update #指定为update，每次启动项目检测表结构有变化的时候会新增字段，表不存在时会 新建，如果指定create，则每次启动项目都会清空数据并删除表，再新建
#        format_sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
    add-properties: false
  activiti:
    #    flase：       默认值。activiti在启动时，会对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常。（生产环境常用）
    #    true：        activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建。（开发时常用）
    #    create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）。（单元测试常用）
    #    drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）。
    database-schema-update: true
    #默认不生成历史表，这里开启
    db-history-used: true
    #在流程引擎启动就激活AsyncExecutor,异步 true  false 关闭  （切记关闭）
    async-executor-activate: false
    #历史登记
    #    none: 不记录历史流程，性能高，流程结束后不可读取
    #    activity: 归档流程实例和活动实例，流程变量不同步
    #    audit: 默认值，在activiti基础上同步变量值，保存表单属性
    #    full: 性能较差，记录所有实例和变量细节变化，最完整的历史记录，如果需要日后跟踪详细可以开启full（一般不建议开启）
    history-level: full

  mail:
    protocol: smtp
    host: 172.30.216.196
    port: 25
    default-encoding: UTF-8

  thymeleaf:
    check-template: true
#      prefix: classpath:/thymeleaf
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML
logging:
  level:
    org:
      activiti:
        engine:
          impl:
            persistence:
              entity: trace

my-config:
  image-path:
    /opt/upload/profile/
  virus-log-path:
    /opt/upload/virus/
  release-path:
    /opt/release/
  # 无需包装请求的url
  whiteList:
    - /user/uploadImage
    - /virus/autoUpload
    - /device/importExcel
    - /device/select
  mail-from: asv.tech@dynabook.com
  send-mail: false